name: Minify source files

on:
  workflow_run:
    workflows: [Sync fork]
    types:
    - completed
  push:
    branches:
    - min
    paths:
    - .github/workflows/minify.yml
    - .darklua.json5
    - source

jobs:
  darklua:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: download-and-format
      run: |
        wget -O darklua-linux.zip https://github.com/seaofvoices/darklua/releases/latest/download/darklua-linux-x86_64.zip
        unzip -o darklua-linux.zip
        chmod +x ./darklua
        git pull
        ./darklua process source source.min.luau

    - uses: EndBug/add-and-commit@v9
      with:
        add: source.min.luau
        message: Minify source files
        committer_name: GitHub Actions
        committer_email: actions@github.com
