name: Sync fork

on:
  schedule:
  - cron: "0 * * * *"
  push:
    branches:
    - min
    paths:
    - .github/workflows/sync.yml

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - run: gh repo sync Epikest/infiniteyield -b min
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}