name: Sync fork
on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - run: gh repo sync Epikest/infiniteyield
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}